#!/usr/bin/env python

def fizz_buzz(input):
    a, b, m = [int(num) for num in input.split(" ")]
    out = []
    for n in range(1, m + 1):
        alt = ""
        for arg in [[a, 'Fizz'], [b, 'Buzz']]:
            alt += arg[1] if not n % arg[0] else ""
        out.append(alt if alt else str(n))
    return " ".join(out)